### ISSUE TITLE
Attend London Elm Meetup on 30th November 19:00 @SkillsMatter

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elm#13]
see: http://www.meetup.com/Elm-London-Meetup/events/235176818/
10 South Place, London, EC2M 2RB

**Comment by nelsonic** [comment]
@SimonLab do you have time/interest to attend the meetup?

**Comment by SimonLab** [comment]
@nelsonic I just reserved by place! see you there

**Comment by iteles** [comment]
<img width="155" alt="screen shot 2016-11-14 at 13 28 00" src="https://cloud.githubusercontent.com/assets/4185328/20266497/35e038d8-aa6e-11e6-9d4e-8b5076507662.png">
@nelsonic Who's your `+1`?

**Comment by nelsonic** [comment]
@iteles I _reserved_ a `+1` in `case` _someone_ wanted to join me ... 😉

**Comment by nelsonic** [comment]
@sohilpandya I _totally_ forgot to put this meetup in my calendar... 😢 
Would you be _interested_ in going tonight...?

**Comment by sohilpandya** [comment]
@nelsonic unfortunately, I'd already made plans for the evening 😢 

Also, this means we have to postpone the evening stand up to start from tomorrow??

**Comment by nelsonic** [comment]
@sohilpandya fair enough. if we can do our meeting this evening from 17:30 - 18:30 we don't _have_ to postpone...

**Comment by sohilpandya** [comment]
That would work! lets reschedule to start at 17:30, @iteles does that work for you?

**Comment by nelsonic** [comment]
the November meetup was _great_!
They haven't announced the next one yet: https://www.meetup.com/Elm-London-Meetup/events/235176818/ but I would _highly_ encourage everyone based in London to go!
