### ISSUE TITLE
Elm V0.18 what's new?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elm#19]
The Elm Compiler version **0.18** was published last Friday. https://github.com/elm-lang/elm-compiler/releases/tag/0.18.0
![elm-lang-compiler-v0 18](https://cloud.githubusercontent.com/assets/194400/20265554/a3868496-aa69-11e6-9e75-5cb1c4b9fed9.png)

But there was no mention of the release on twitter: https://twitter.com/elmlang
or on the elm blog: http://elm-lang.org/blog

So, the _question_ is: is it "ready" to be used? or should we still be using `v0.17.1` for the code in this tutorial?

**Comment by SimonLab** [comment]
A new blog post on how to debug with 0.18 has been published on the elm blog: http://elm-lang.org/blog/the-perfect-bug-report

**Comment by nelsonic** [comment]
`Ran into a single quote in a variable name. This was removed in 0.18!` 🎉

**Comment by nelsonic** [comment]
Upgrade instructions: https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.18.md

**Comment by nelsonic** [comment]
I *printed* off the "official" elm guide so that's I can make notes and read offline (sans distractions)
If anyone 'else' is interested in a 
![img_1307](https://cloud.githubusercontent.com/assets/194400/20389587/363efd5e-acc2-11e6-8599-adf766f6b071.JPG)
physical copy of the guide, let me know.

**Comment by nelsonic** [comment]
Really Looking forward to v0.19 https://github.com/elm-lang/projects/blob/master/roadmap.md ...
