### ISSUE TITLE
Elm Frontend Masters Workshop by Richard Feldmen

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elm#24]
Rather than re-invent and duplicate effort, we should _recommend_ that people do @rtfeldman's Workshop!
+ https://frontendmasters.com/workshops/elm/ 
+ https://github.com/rtfeldman/elm-workshop

He's got _way_ more experience than any of us and his workshop is _thorough_!

**Comment by andrewMacmurray** [comment]
@nelsonic have been working through this and they're great, but they've not been updated to `0.18` yet, the `http` and `task` stuff is currently frying my brain 😭

**Comment by nelsonic** [comment]
@andrewMacmurray yeah, the `videos` are _unlikely_ to be updated to `v0.18` so the best we can do is _document_ the differences here in issues and/or submit a PR to @rtfeldman's `elm-workshop` repo...

**Comment by nelsonic** [comment]
@andrewMacmurray have you seen @rtfeldman's recent update to the Workshop code: 😉 
![upgrade-everything-to-0 18](https://cloud.githubusercontent.com/assets/194400/21488709/d500ca08-cbda-11e6-8fdf-2bf86c533542.png)

https://github.com/rtfeldman/elm-workshop/commit/7fc5118626500e94c9da9764f496e1bd22cbf712

**Comment by andrewMacmurray** [comment]
@nelsonic that's awesome 😍  will have a look through

**Comment by nelsonic** [comment]
See: https://github.com/rtfeldman/elm-workshop/issues/8

**Comment by ImsirovicAjdin** [comment]
@nelsonic, I'd like to transcribe the whole rest of the workshop.

**Comment by nelsonic** [comment]
@ImsirovicAjdin the workshop is going to be "_obsolete_" soon as the new version of Elm (v.0.19) will be released which will change some of the code. 
if you would like to help with improving the @dwyl `learn-elm` repo or any of our other tutorials, please dive in! 👍
