### ISSUE TITLE
London Elm Meetup 13th February 19:00 at Songkick: Third Floor, 12-18 Hoxton Street, N1 6NG, London

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elm#34]
The London Elm Meetup has just been announced and spaces will be taken _fast_! 💨 

https://www.meetup.com/Elm-London-Meetup/events/236845874/ 📝 

> CC: @katbow @sofiapoh @jsms90 @iteles @NataliaLKB @tsop14 @Cleop @andrewMacmurray @ivanmauricio @shouston3 @sohilpandya @eliascodes 
the last one was really good ... ask @SimonLab and @jackfranklin ... if you can make it, go! 📆

**Comment by andrewMacmurray** [comment]
done!

**Comment by jackfranklin** [comment]
🎉 hope to see you there :)

**Comment by sohilpandya** [comment]
Woohoo. Thanks @nelsonic. Gutted I missed the last one. Can't wait for it. 

Might have to finish that booking time. 🎉

**Comment by shouston3** [comment]
Done. See you all there

**Comment by katbow** [comment]
I'm there!

**Comment by sofiapoh** [comment]
Done! See you guys there

**Comment by NataliaLKB** [comment]
Exciting! I should be able to see you there!

**Comment by JMurphyWeb** [comment]
On the waiting list. Will gate crash if necessary.

**Comment by nelsonic** [comment]
@JMurphyWeb yeah, those spaces fill up fast...
@jackfranklin is _hosting_ and he _might_ be able to give you some insight on numbers.
If @iteles can't make it, you can be my "+1" ... 😉 
It's going to be "freakin' awesome" (_I think that's the technical term_) 
cause it's a hands-on workshop and we're working on Elm with WebSockets so...

**Comment by tbtommyb** [comment]
on the waiting list too

**Comment by jackfranklin** [comment]
We usually have enough drop outs that those on the wait list should be OK. If you're on the wait list the day before still just ping me directly and I'll see how we're looking.

**Comment by njsfield** [comment]
on waiting list too- thanks @jackfranklin !

**Comment by jackfranklin** [comment]
Just to let you all know there's another meetup tonight :)  It's not at Songkick though - meetup page has all the info. Hope to see you there!

**Comment by gabrielperales** [comment]
Hi @jackfranklin, do you know where I can find the slides from the last meetup? It would be also great If somehow I can have those slides from tonight's meetup.
