### ISSUE TITLE
Reference "Official guide" _after_ DWYL's 5 minute guide

### ISSUE THREAD

**Issue by jsms90** [dwyl/learn-elm#41]
Because of the ordering on the how section
> ## How?
> The best place to start is with the "_Official Guide_": http://guide.elm-lang.org/get_started.html <br />
we have _condensed_ the steps into the **5-minute** instructions below:

I think people are quite likely to click on the link and start working through the installation guide, before even reading "we have condensed the steps below" - something I see really often when people are going through online tutorials.

If you think it is better/easier for people to follow DWYL's condensed version (which I definitely do), I would suggest you change the order, so that you reference the official guide at the end

**Comment by JoseCage** [comment]
👍
I think @jsms90  is right.

> If you think it is better/easier for people to follow DWYL's condensed version (which I definitely do), I would suggest you change the order, so that you reference the official guide at the end

**Comment by iteles** [comment]
@jsms90 Great shout 👍
