### ISSUE TITLE
what is elm-format and how do I use it with my editor/IDE?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elm#43]
> should this go in the ***How***? section of the readme? 🤔 

### Elm Format

`elm-format` formats your code so that it is _consistent_ with the `community standard` format.
Let go of your _preconceptions_ of how code `should` look in _other_ languages, `elm` is your chance to _embrace_ a new _paradigm_ so **don't _waste time_** discussing `spaces vs. tabs?` or `one statement per line?` or `newline after code block?` _Simply_ use the `community standard` and _**focus** on your **feature**_. 

See: https://github.com/avh4/elm-format
Editor integrations: https://github.com/avh4/elm-format#editor-integration

**Comment by lucymonie** [comment]
I love Elm Format and I agree that this should be added to the How section.

Several people in FAC9 had trouble with the PATH aspect when installing Elm format, and you need to make sure that you install it in the right place so Atom can find it. There are good instructions for setting up an Elm dev environment here: https://github.com/knowthen/elm/blob/master/DEVSETUP.md

**Comment by lucymonie** [comment]
I was thinking about this some more and I'm wondering if it's better to add a section to the README after the global install section rather than in 'How'? I'm happy to submit a PR for this if that would be useful.

**Comment by nelsonic** [comment]
@lucymonie that would be _very_ useful. thanks! ❤️
