### ISSUE TITLE
Elm learning curve

### ISSUE THREAD

**Issue by lucymonie** [dwyl/learn-elm#45]
Dwyl's learn-elm tutorial instructs you to clone the repo and fire up elm reactor after changing one piece of text in one file, and then pause to reflect on the experience. The next step is to begin **An Introduction to Elm**, which starts with some playing around in the repl and then swiftly moves into quite complex tasks. I am concerned that the curve is too steep and that some may be discouraged and give up.

I would suggest that people do the following:
1. Core language: https://guide.elm-lang.org/core_language.html
2. Elm architecture: https://guide.elm-lang.org/architecture/
3. Elm for Beginners: http://courses.knowthen.com/p/elm-for-beginners
4. Elm architecture tutorial: https://guide.elm-lang.org/architecture/user_input/

**Comment by gabrielperales** [comment]
I agree. But I would introduce solve some exercism problems as step2.

It is very frustrating coming from JavaScript and trying to build an application without having learnt the elm's core library, so exercism will help you to settle the step 1.

**Comment by nelsonic** [comment]
@lucymonie & @gabrielperales  _great_ suggestion(s)! 
please feel free to PR any improvements. thanks! 😍

**Comment by lucymonie** [comment]
Shall do @nelsonic. Which exercism problems would you insert @gabrielperales?

**Comment by gabrielperales** [comment]
@lucymonie I'm doing all of them. One by one in order. The more you do the more you learn :)

**Comment by gabrielperales** [comment]
I also have found this repo https://github.com/robertjlooby/elm-koans . Those koans are also a good way to settle down the knowledge 😄 .

**Comment by newswim** [comment]
Elm-Koans are great! I also really liked [Python-Koans](https://github.com/gregmalcolm/python_koans).

**Comment by lucymonie** [comment]
I'm loving this thread! So @gabrielperales would you make the list:

1. Core language: https://guide.elm-lang.org/core_language.html
2. Exercism: http://exercism.io/languages/elm/about
3. Elm for Beginners: http://courses.knowthen.com/p/elm-for-beginners
4. Elm architecture tutorial: https://guide.elm-lang.org/architecture/

Would you include the koans? If so, where?

**Comment by gabrielperales** [comment]
@lucymonie koans are at the same level of Exercism. But I think the list is perfect as you did it 👍

**Comment by nelsonic** [comment]
Anyone _finding_ this thread and struggling with The Elm Architecture ("TEA") 
should checkout: https://github.com/dwyl/learn-elm-architecture-in-javascript 😉
