### ISSUE TITLE
Add examples of Elm ports

### ISSUE THREAD

**Issue by gabrielperales** [dwyl/learn-elm#62]
Sometimes you are going to need interoperate with javascript, maybe because you need access to some native APIs and there isn't any elm library to interop with that native api yet. Or maybe because you already have javascript code and you want Elm to be able to communicate with it. 

For those cases, Elm comes with Elm ports, and they will allow us do that communication.

**Comment by gabrielperales** [comment]
I found [these slides](https://xarvh.github.io/talk-elm-ports/) from @xarvh talking about elm ports. I think I'm going take one of those examples for this repo.

**Comment by newswim** [comment]
Amazing slides, I love that the deck was also written in Elm.

![Elm vs. JavAsCript](https://raw.githubusercontent.com/xarvh/talk-elm-ports/master/none.png)

🤣

**Comment by gabrielperales** [comment]
I've done [this example repo](https://github.com/gabrielperales/elm-soundcloud-player) to learn about elm ports. Maybe I should do something more focused just on elm ports to add it to this repo, but you can start having a look.
