### ISSUE TITLE
Add some info/links about routing?

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-elm#90]
Today we spent quite a while struggling with routing in elm (on [this project](https://github.com/ZooeyMiller/rounded-app)) and found that there aren't any links or info about routing Elm in this tutorial, where it could be really useful!
Assigning myself as I'd quite like to make a PR with this info (may not be for a few days).

**Comment by nelsonic** [comment]
@ZooeyMiller an addition/update would be great!
did you read: https://www.elm-tutorial.org/en/07-routing/02-routing.html ?

**Comment by ZooeyMiller** [comment]
@nelsonic Didn't find that but that's helpful, thank you! 
We used Navigation and through the docs and some trial and error came to a working solution.
